# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps: 
  - script: echo building project
    displayName: 'Build'
  
  - script: echo  testing project 
    displayName: 'Test'
  
- job: job2
  dependsOn: job1
  steps: 
  - script: echo Releasing to QA 
    displayName: 'Release to QA' 

- job: job3
  dependsOn: job2
  steps: 
  - script: echo Releasing to preprod 
    displayName: 'Release to preprod' 

