# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
      - script: echo Build FirstJob
        displayName: 'FirstBuildJobStep'
  - job: SecondJob
    steps:
      - script: echo Build SecondJob
        displayName: 'SecondBuildJobStep'
  
- stage: Test
  jobs: 
  - job: TestJob
    steps: 
    - script: echo testing the build
      displayName: 'TestBuildStep'
 
- stage: DevDeploy
  dependsOn:
  - Build
  - Test
  jobs: 
  - job: DevDeployJob
    steps:
    - script: echo deploying to dev
      displayName: 'DevDeployStep'
     
- stage: QADeploy
  dependsOn:
  - Build
  - Test 
  jobs: 
  - job: QADeployJob
    steps:
    - script: echo deploying to qa
      displayName: 'QADeployStep'

- stage: ProdDeploy
  dependsOn: 
  - QADeploy
  - DevDeploy
  jobs: 
  - job: ProdDeployJob
    steps:
    - script: echo deploying to prod
      displayName: 'ProdDeployJobStep'
       
   
   
