# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
      - script: echo Build FirstJob
        displayName: 'Firstjob'
  - job: SecondJob
    steps:
      - script: echo Build SecondJob
        displayName: 'Firstjob'
     

- stage: DevDeploy
- stage: QADeploy
- stage: ProdDeploy

container::
- script: echo job1 step1
  displayName: 'Run a one-line script'


