# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
      - script: echo Build FirstJob
        displayName: 'FirstBuildJob'
  - job: SecondJob
    steps:
      - script: echo Build SecondJob
        displayName: 'SecondBuildJob'
  
 - stage: Test
   jobs: 
   - job: TestJob
     steps: 
     - script: testing the build
       displayName: 'TestBuild'
 
 - stage: DevDeploy
   jobs: 
   - job: DevDeploy
     steps:
     - script: echo Deploying to Dev
       displayName: 'DevDeploy'
     
  - stage: QADeploy
    jobs: 
    - job: QADeploy
      steps:
       - script: echo Deploying to QA
         displayName: 'QADeploy'
       
   
   
