name: build and copy  

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
   ls -R $(System.DefaultWorkingDirectory)
   ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files from working directory to Staging Directory'
  
- bash: |
     ls -R $(System.DefaultWorkingDirectory)
     ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'Run a one-line script'
 
